- .gitignore
- backend/.sample-env
- backend/index.js
- backend/package.json
* moving variables to .env file
* adding a sample-env file
* modifying start script to add --env-file flag for env support
> env variables related changes

- backend/index.js
- backend/package-lock.json
- backend/package.json
* install cors package
* use in inside app
> add cors support

- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Properties/Properties.jsx
- frontend/real-estate/src/Components/Property/Property.jsx
Refactoring
* move property-item to seperate component 
* simplify search logic for readability
* modify dummy data
> move property-item component to seperate file & simplify search logic

- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Add Property/addProperty.css
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Properties/Properties.jsx
- frontend/real-estate/src/Components/Properties/PropertyEndpoints.js
- frontend/real-estate/src/Components/Properties/PropertyForm.js
- frontend/real-estate/src/Components/Properties/properties.css
- frontend/real-estate/src/Components/Topbar/topbar.css
* add property component
* object for storing field data
* endpoints for each section of form
* styling existing and new components
> Add property component added and other

- backend/database/models/property.js
- backend/routes/property.js
- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Add Property/addProperty.css
- frontend/real-estate/src/Components/Properties/PropertyEndpoints.js
- frontend/real-estate/src/Components/Sidebar/sidebar.css
* backend
* replacing boolean type with text in property schema
* post route to handle property data
* frontend
* Add Property Component
* moving `formData` state out of `FormComponent` to parent component
* making form a controlled component based on `formData` state
* styling based on active section of form in navigation bar
* function that sends a post request on submitting property data
* styling changes
* styling changes in sidebar
> styling and add property component

- backend/routes/property.js
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Properties/PropertyEndpoints.js
- frontend/real-estate/src/Components/Topbar/TopBar.jsx
* backend
* setting up `get-property` route for fetching property data
* frontend
* making a fetch request to `/get-property` route to get properties of logged in user
* replacing username with useremail in user info panel aka topbar
> Add property endpoint

- backend/database/models/property.js
- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Add Property/addProperty.css
- frontend/real-estate/src/Components/Base/Base.jsx
* changed property schema to include more data
* added hover states to buttons
* function to populate some meta data for form
* state to hold user properties
> get property related changes

- backend/routes/property.js
- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Edit Property/EditProperty.jsx
- frontend/real-estate/src/Components/Properties/Properties.jsx
- frontend/real-estate/src/Components/Properties/PropertyEndpoints.js
- frontend/real-estate/src/Components/Properties/properties.css
- frontend/real-estate/src/Components/Property/Property.jsx
* route to update property data
* edit property component
* styling changes
* add property component modified to be used for editing as well
* endpoint for editing property added
> add edit property feature

- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Add Property/addProperty.css
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Display Property/DisplayProperty.jsx
- frontend/real-estate/src/Components/Display Property/displayProperty.css
- frontend/real-estate/src/Components/Property/Property.jsx
- frontend/real-estate/src/Components/Topbar/topbar.css
* component to render property details
* styling for component
* existing styling changes
* buttons to render edit/home Components
* add route for display component
* attach display functionality to view icon
> add display property feature

- backend/database/dbFun.js
- backend/routes/property.js
- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Display Property/DisplayProperty.jsx
- frontend/real-estate/src/Components/Display Property/displayProperty.css
- frontend/real-estate/src/Components/Property/Property.jsx
* modify image upload function
* add property image to display Property component
* minor issue fixes
> change image upload

- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Edit Property/EditProperty.jsx
* on edit/adding of new property updated values will render on home screen without reload.
* a flag state to hold edit/add status
* updates on succcessful changes
* fetches latest data on render
> fix rendering latest data on update

- backend/database/dbFun.js
- backend/package-lock.json
- backend/package.json
- backend/routes/user.js
function to decrpt/encrypt password
> encrypted user password in db

- frontend/real-estate/package-lock.json
- frontend/real-estate/package.json
- frontend/real-estate/src/Components/Display Property/DisplayProperty.jsx
- frontend/real-estate/src/Components/Loader/Loader.jsx
- frontend/real-estate/src/Components/Loader/loader.css
* adding dependency for loader Component
* refactoring Display Property Component for clarity
* styling for loader
> Add loader

- frontend/real-estate/src/Components/Auth/Login.jsx
- frontend/real-estate/src/Components/Auth/Register.jsx
- frontend/real-estate/src/Components/Auth/auth.css
* state to hold loading state of component
* changing font size on hover of both sign up, sign in buttons and links
* during fetch request, colour of buttons is faded and are disabled to prevent multiple click for better UX
* additonal sleep functions to simulate slow network calls
> improve UX for sign in and sign up button

- frontend/real-estate/.sample-env
- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Auth/Login.jsx
- frontend/real-estate/src/Components/Auth/Register.jsx
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Display Property/DisplayProperty.jsx
- frontend/real-estate/src/Components/Properties/PropertyEndpoints.js
* deleting `PropertyEndpoints.js`
* introducing .env file
* using endpoints from .env file 
* add a sample-env file
> replacing harcoded api endpoints with env vars

- LICENSE
- README.md
- frontend/real-estate/src/Components/Auth/Login.jsx
- frontend/real-estate/src/Components/Auth/Register.jsx
- frontend/real-estate/src/Components/Auth/auth.css
* improve UX for sign in and sign up button (#45)
* state to hold loading state of component
* changing font size on hover of both sign up, sign in buttons and links
* during fetch request, colour of buttons is faded and are disabled to prevent multiple click for better UX
* additonal sleep functions to simulate slow network calls
* Create LICENSE
adds LICENSE document to project
* add README (#46)
> syncing with prod

- backend/database/dbFun.js
- backend/routes/property.js
- backend/routes/user.js
- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Display Property/DisplayProperty.jsx
- frontend/real-estate/src/Components/Edit Property/EditProperty.jsx
- frontend/real-estate/src/Components/Topbar/TopBar.jsx
* remove console logs
* unused imports
* comments
> remove console logs and no longer required imports

- frontend/real-estate/package-lock.json
- frontend/real-estate/package.json
- frontend/real-estate/src/Components/Display Property/DisplayProperty.jsx
- frontend/real-estate/src/Components/Display Property/displayProperty.css
* adds fontawesome dependency
* conditonal rendering of image/svg element
* styling of property image
> load backup svg icon on image failure

- frontend/real-estate/src/Components/Add Property/AddProperty.jsx
- frontend/real-estate/src/Components/Base/Base.jsx
- frontend/real-estate/src/Components/Edit Property/EditProperty.jsx
* state to handle loading status of property list component
* conditional rendering based on state
> loader on home page load until property list is rendered

- frontend/real-estate/src/Components/Auth/auth.css
add media query for login/register container
> make login/register responsive
